volumes:
  mysql-data: {}

services:
  app:
    image: php:8.4-apache
    container_name: git-app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.git.rule=Host(`git.dev.local.test`)"
      - "traefik.http.routers.git.entrypoints=web"
      - "traefik.http.services.git.loadbalancer.server.port=80"
    command: >
      sh -c "
             groupmod -g 1000 www-data &&
             usermod -u 1000 www-data &&

             echo '<Directory /var/www/html>' > /etc/apache2/conf-enabled/allow-override.conf &&
             echo 'AllowOverride All' >> /etc/apache2/conf-enabled/allow-override.conf &&
             echo '</Directory>' >> /etc/apache2/conf-enabled/allow-override.conf &&
             sed -i 's|DocumentRoot .*|DocumentRoot /var/www/html/public|' /etc/apache2/sites-available/000-default.conf &&

             a2enmod rewrite &&
             exec apache2-foreground"
    networks:
      - web

  vite:
    image: node:18
    container_name: git-vite
    working_dir: /var/www/html
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
    volumes:
      - ./:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.git-vite.rule=Host(`vite.git.dev.local.test`)"
      - "traefik.http.routers.git-vite.entrypoints=web"
      - "traefik.http.services.git-vite.loadbalancer.server.port=5173"
    networks:
      - web

networks:
  web:
    external: true
